import { defineConfig } from "eslint/config";
import json from "@eslint/json";
import tsparser from "@typescript-eslint/parser";
import obsidianmd from "eslint-plugin-obsidianmd";
import { PlainTextParser } from "eslint-plugin-obsidianmd/dist/lib/plainTextParser.js";

export default defineConfig([
  {
    ignores: [
      "dist/**",
      "backup-before-migration/**",
      "src/**/*.test.ts",
      "src/**/*.spec.ts",
      "src/**/__tests__/**",
      "src/demo/**",
      "src/tests/**",
      "src/**/*.json",
    ],
  },
  ...obsidianmd.configs.recommendedWithLocalesEn,
  {
    files: [
      "src/main.ts",
      "src/views/Epub*.ts",
      "src/views/epub-view-host.ts",
      "src/views/DeferredLeafRedirectController.ts",
      "src/config/performance.ts",
      "src/types/obsidian-extensions.ts",
      "src/services/epub/**/*.ts",
      "src/services/navigation/**/*.ts",
      "src/services/ui/**/*.ts",
      "src/components/epub/**/*.ts",
      "src/components/modals/Epub*.ts",
      "src/components/settings/EpubSettingsTab.ts",
      "src/config/security-config.ts",
      "src/services/premium/PremiumFeatureGuard.ts",
      "src/services/ai/ai-host.ts",
      "src/services/identifier/WeaveIDGenerator.ts",
      "src/stores/ai-config.store.ts",
      "src/stores/epub-active-document-store.ts",
      "src/config/paths.ts",
      "src/types/license.ts",
      "src/types/utility-types.ts",
      "src/utils/card-export-utils.ts",
      "src/utils/blob-url-text.ts",
      "src/utils/dom-instance-of.ts",
      "src/utils/obsidian-document-dom.ts",
      "src/utils/mobile-modal-bounds.ts",
      "src/utils/obsidian-workspace-utils.ts",
      "src/utils/electron-screenshot-access.ts",
      "src/utils/directory-utils.ts",
      "src/utils/vault-local-storage.ts",
      "src/utils/epub-leaf-utils.ts",
      "src/utils/FolderSuggest.ts",
      "src/utils/i18n.ts",
      "src/utils/license-state.ts",
      "src/utils/licenseManager.ts",
      "src/utils/license-sync-bridge.ts",
      "src/utils/logger.ts",
      "src/utils/notifications.ts",
      "src/utils/obsidian-api-safe.ts",
      "src/utils/obsidian-confirm.ts",
      "src/utils/plugin-access.ts",
      "src/utils/plugin-license.ts",
      "src/utils/smart-retry.ts",
      "src/utils/sync-safe-filename.ts",
      "src/utils/view-location-utils.ts",
      "src/utils/workspace-navigation.ts",
      "src/utils/yaml-utils.ts",
    ],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        project: "./tsconfig.eslint.obsidian.json",
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "obsidianmd/ui/sentence-case": [
        "warn",
        {
          brands: ["Weave", "Obsidian", "Markdown"],
          acronyms: ["AI", "API", "HTTP", "HTTPS", "IR", "PDF", "EPUB", "PDF++", "UUID", "URL", "YAML"],
        },
      ],
      "@typescript-eslint/no-floating-promises": "warn",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unnecessary-type-assertion": "off",
      "@typescript-eslint/no-unsafe-enum-comparison": "off",
      "@typescript-eslint/await-thenable": "off",
      "@typescript-eslint/no-misused-promises": "off",
      "@typescript-eslint/restrict-template-expressions": "off",
      "@typescript-eslint/no-redundant-type-constituents": "off",
      "@typescript-eslint/no-base-to-string": "off",
      "@typescript-eslint/only-throw-error": "off",
      "@typescript-eslint/prefer-promise-reject-errors": "off",
      "@typescript-eslint/no-deprecated": "off",
      "@typescript-eslint/no-duplicate-type-constituents": "off",
      "@typescript-eslint/no-unsafe-function-type": "off",
      "@typescript-eslint/no-this-alias": "off",
      "import/no-extraneous-dependencies": "off",
      "no-undef": "off",
      "no-empty": "off",
      "no-useless-escape": "off",
      "no-case-declarations": "off",
      "no-control-regex": "off",
      "no-misleading-character-class": "off",
      "no-constant-condition": "off",
    },
  },
  {
    files: ["src/**/*.ts"],
    rules: {
      "@typescript-eslint/no-unsafe-assignment": "warn",
      "@typescript-eslint/no-unsafe-return": "warn",
      "@typescript-eslint/no-unnecessary-type-assertion": "warn",
      "@typescript-eslint/no-unsafe-enum-comparison": "warn",
      "@typescript-eslint/await-thenable": "warn",
      "@typescript-eslint/no-deprecated": "error",
    },
  },
    {
    files: [
      "src/utils/obsidian-document-dom.ts",
      "src/services/epub/FoliateReaderService.ts",
      "src/services/epub/foliate-blob-markup-normalizer.ts",
    ],
    rules: {
      "obsidianmd/prefer-create-el": "off",
    },
  },
  {
    files: ["manifest.json"],
    language: "json/json",
    plugins: {
      obsidianmd,
      json,
    },
    rules: {
      "no-irregular-whitespace": "off",
      "obsidianmd/validate-manifest": "error",
    },
  },
  {
    files: ["LICENSE"],
    plugins: {
      obsidianmd,
    },
    languageOptions: {
      parser: PlainTextParser,
      parserOptions: {
        extraFileExtensions: [""],
      },
    },
    rules: {
      "no-irregular-whitespace": "off",
      "no-unused-vars": "off",
      "no-undef": "off",
      "obsidianmd/validate-license": "error",
    },
  },
]);
